# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: bf3ada80b286578cc330dd5382d51a889f9cc16744e9b9a9f4e483cb8b9c87fd0219e7c1086bdcefd564b3f12b516a2e7e6164e3b4317e104b8071ff6952b964

test:
  secret_key_base: 449515fa8ef827fa43403dc90c1069d924c2d55b67a19453538a2baa2ed97ff786d7969ca958329c12a79587bae5735b7c2585622b9d462d13bf78f41792337f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
